### ISSUE TITLE
Time series ordering problems?

### ISSUE THREAD

**Issue by alistairking** [CAIDA/watchtower-sentry#25]
I'm going to use this issue to collect some notes about trying to run watchtower-sentry v2 against the BGP and ping-slash24 data sources.

I left a test run going for BGP, and the process crashed with:
```
09:26:27.992 watchtower.sentry.filters.MovingStat 323:MainThread WARNING : removing extra old item (b'bgp.prefix-visibility.asn.32779.v4.visibility_threshold.min_50%_ff_peer_asns.visible_slash24_cnt', 9, 1596814800)
09:26:27.998 watchtower.sentry.filters.MovingStat 323:MainThread WARNING : removing extra old item (b'bgp.prefix-visibility.asn.19312.v4.visibility_threshold.min_50%_ff_peer_asns.visible_slash24_cnt', 2, 1596814800)
09:26:28.003 watchtower.sentry.filters.MovingStat 323:MainThread WARNING : removing extra old item (b'bgp.prefix-visibility.asn.60325.v4.visibility_threshold.min_50%_ff_peer_asns.visible_slash24_cnt', 4, 1596814800)
09:26:28.009 watchtower.sentry.filters.MovingStat 323:MainThread WARNING : removing extra old item (b'bgp.prefix-visibility.asn.205712.v4.visibility_threshold.min_50%_ff_peer_asns.visible_slash24_cnt', 1, 1596814800)
...
09:26:28.028 watchtower.sentry    323:MainThread CRITICAL: IndexError:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/watchtower.sentry-2.0-py3.6.egg/watchtower/sentry/sentry.py", line 181, in cli
    exitstatus = main(cmdline_options)
  File "/usr/local/lib/python3.6/dist-packages/watchtower.sentry-2.0-py3.6.egg/watchtower/sentry/sentry.py", line 143, in main
    s.run()
  File "/usr/local/lib/python3.6/dist-packages/watchtower.sentry-2.0-py3.6.egg/watchtower/sentry/sentry.py", line 127, in run
    self.run_last_mod()
  File "/usr/local/lib/python3.6/dist-packages/watchtower.sentry-2.0-py3.6.egg/watchtower/sentry/sinks/AlertKafka.py", line 113, in run
    for entry in self.gen():
  File "/usr/local/lib/python3.6/dist-packages/watchtower.sentry-2.0-py3.6.egg/watchtower/sentry/filters/TimeOrderChecker.py", line 36, in run
    for (key, val, t) in self.gen():
  File "/usr/local/lib/python3.6/dist-packages/watchtower.sentry-2.0-py3.6.egg/watchtower/sentry/filters/MovingStat.py", line 370, in run
    data.insert_remove(newval, oldest[0])
  File "/usr/local/lib/python3.6/dist-packages/watchtower.sentry-2.0-py3.6.egg/watchtower/sentry/filters/MovingStat.py", line 191, in insert_remove
    _sortedlist_add_remove(self.values, ins_val, rm_val)
  File "/usr/local/lib/python3.6/dist-packages/watchtower.sentry-2.0-py3.6.egg/watchtower/sentry/filters/MovingStat.py", line 100, in _sortedlist_add_remove
    slist[left] = additem
IndexError: list assignment index out of range
```

This smells like two problems:
1. why does it need to "remove extra old item"?
2. why does it crash when doing this?

**Comment by alistairking** [comment]
I think I was using this config: https://github.com/CAIDA/ioda-watchtower-deploy/blob/92a1eb8ff568952df8ed822a6eaa0cafef2eb6a1/config/sentry.bgp.config.yaml
